# Generated by Django 2.0.2 on 2018-03-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('signup_from', models.DateTimeField()),
                ('signup_to', models.DateTimeField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
