# Generated by Django 2.0.2 on 2018-03-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='label',
            field=models.TextField(default='Label', max_length=126),
            preserve_default=False,
        ),
    ]
